# Generated by Django 4.2.7 on 2023-12-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.FloatField()),
                ('campo2', models.FloatField()),
                ('campo3', models.FloatField()),
                ('campo4', models.FloatField()),
                ('campo5', models.FloatField()),
                ('resultado', models.CharField(max_length=255)),
            ],
        ),
    ]
